# Generated by Django 4.2.6 on 2024-07-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "factory"),
                            ("2", "mass retailer"),
                            ("3", "self-employed"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        blank=True, choices=[(0, "0"), (1, "1"), (2, "2")], null=True
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("country", models.CharField(max_length=150, verbose_name="Country")),
                ("city", models.CharField(max_length=150, verbose_name="City")),
                ("street", models.CharField(max_length=150, verbose_name="Street")),
                (
                    "house_number",
                    models.PositiveSmallIntegerField(verbose_name="Number of a house"),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=11,
                        verbose_name="Debt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "the_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="electronics_shop.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("model", models.CharField(max_length=150, verbose_name="Model")),
                (
                    "date",
                    models.DateField(
                        blank=True, default="", null=True, verbose_name="Release date"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_shop.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("title", "model"),
            },
        ),
    ]
